services:
  backend:
    image: wankou/leetcode-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TrackerDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SECRET_KEY: 2E1uOv9E6zblcNUGWcKpvmkKYI5D6tJ7Rfcd2x2jsnE=

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: TrackerDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    image: wankou/leetcode-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend



volumes:
  pgdata:
