spring.datasource.url=jdbc:postgresql://db:5432/TrackerDb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

app.secret-key=${SECRET_KEY:2E1uOv9E6zblcNUGWcKpvmkKYI5D6tJ7Rfcd2x2jsnE=}
app.allowed-origins=http://localhost:5173

server.port=8080
server.address=0.0.0.0